<!DOCTYPE html>
<html lang="en">

<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8">
	<title>Page not found at /update_order/29/</title>
	<meta name="robots" content="NONE,NOARCHIVE">
	<style type="text/css">
		html * {
			padding: 0;
			margin: 0;
		}

		body * {
			padding: 10px 20px;
		}

		body * * {
			padding: 0;
		}

		body {
			font: small sans-serif;
			background: #eee;
			color: #000;
		}

		body>div {
			border-bottom: 1px solid #ddd;
		}

		h1 {
			font-weight: normal;
			margin-bottom: .4em;
		}

		h1 span {
			font-size: 60%;
			color: #666;
			font-weight: normal;
		}

		table {
			border: none;
			border-collapse: collapse;
			width: 100%;
		}

		td,
		th {
			vertical-align: top;
			padding: 2px 3px;
		}

		th {
			width: 12em;
			text-align: right;
			color: #666;
			padding-right: .5em;
		}

		#info {
			background: #f6f6f6;
		}

		#info ol {
			margin: 0.5em 4em;
		}

		#info ol li {
			font-family: monospace;
		}

		#summary {
			background: #ffc;
		}

		#explanation {
			background: #eee;
			border-bottom: 0px none;
		}

		pre.exception_value {
			font-family: sans-serif;
			color: #575757;
			font-size: 1.5em;
			margin: 10px 0 10px 0;
		}
	</style>
</head>

<body>
	<div id="summary">
		<h1>Page not found <span>(404)</span></h1>
		<pre class="exception_value">No Order matches the given query.</pre>
		<table class="meta">
			<tr>
				<th>Request Method:</th>
				<td>PATCH</td>
			</tr>
			<tr>
				<th>Request URL:</th>
				<td>http://127.0.0.1:8000/update_order/29/</td>
			</tr>

			<tr>
				<th>Raised by:</th>
				<td>item_menu.views.update_order</td>
			</tr>

		</table>
	</div>
	<div id="info">

		<p>
			Using the URLconf defined in <code>Zomato_app_django.urls</code>,
			Django tried these URL patterns, in this order:
		</p>
		<ol>

			<li>

				admin/


			</li>

			<li>





				[name='dish_list']

			</li>

			<li>




				add_dish
				[name='add_dish']

			</li>

			<li>




				remove_dish/&lt;int:dish_id&gt;/
				[name='remove_dish']

			</li>

			<li>




				update/&lt;int:dish_id&gt;
				[name='update']

			</li>

			<li>




				take_order/
				[name='take_order']

			</li>

			<li>




				display_orders
				[name='display_orders']

			</li>

			<li>




				update_order/&lt;int:order_id&gt;/
				[name='update_order']

			</li>

		</ol>
		<p>

			The current path, <code>update_order/29/</code>,

			matched the last one.
		</p>

	</div>

	<div id="explanation">
		<p>
			Youâ€™re seeing this error because you have <code>DEBUG = True</code> in
			your Django settings file. Change that to <code>False</code>, and Django
			will display a standard 404 page.
		</p>
	</div>
</body>

</html>